### ISSUE TITLE
Support inferring shader stage from files named `.<<stage>>.glsl`

### ISSUE THREAD

**Issue by alex-tdrn** [Ralith/vk-shader-macros#12]
Hello, glslang supports inferring the stage from files ending in `.<<stage>>.glsl`, for example `shader.frag.glsl` and `shader.vert.glsl`. 

Would there be interest in this feature? I could try to create a pull request for this, but it seems to be not so straightforward, so I thought I'd make an issue to see whether this is desired first. 

By the way this is an amazingly useful library for learning vulkan <3

**Comment by Ralith** [comment]
Sure, that seems reasonable. It should just be a matter of tweaking the extension-handling path here:
https://github.com/Ralith/vk-shader-macros/blob/af441419bab7ba1335e1620998e5b23a26c72676/src/build.rs#L184-L192

**Comment by alex-tdrn** [comment]
Implemented in https://github.com/Ralith/vk-shader-macros/pull/11
