### ISSUE TITLE
Enable debug info in non release build

### ISSUE THREAD

**Issue by Yamakaky** [Ralith/vk-shader-macros#4]
It would be nice to have `debug` and `optimize: zero` enabled in debug builds.

**Comment by Ralith** [comment]
I like this idea, but I haven't found a good way for the proc macro to determine whether it's being used in a debug build. Maybe a feature flag to override the default level?

**Comment by Yamakaky** [comment]
A global switch would work too!

**Comment by Ralith** [comment]
Added a feature `default-optimize-zero` in 0.2.4.
